import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { cssTokensFor, isPrimitive } from './lib/css-tokens.js';

const ROOT = path.resolve(import.meta.dirname, '..');
const matrix = JSON.parse(readFileSync(path.join(ROOT, 'config/matrix.json'), 'utf8'));
const pkg = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

if (matrix.modes.length !== 2 || !matrix.modes.includes('light') || !matrix.modes.includes('dark')) {
  throw new Error('CSS output assumes exactly the modes ["light", "dark"] (light-dark()).');
}

/** Resolve one context (situation name or 'base') into name → merged CSS value. */
async function mergedValues(context) {
  const [light, dark] = await Promise.all(
    ['light', 'dark'].map(async (mode) => (await cssTokensFor(context, mode)).filter((t) => !isPrimitive(t))),
  );
  const darkValues = new Map(dark.map((token) => [token.name, token.$value]));

  return new Map(
    light.map((token) => {
      const lightValue = token.$value;
      const darkValue = darkValues.get(token.name);
      if (darkValue === undefined) {
        throw new Error(`${context}: token ${token.name} exists in light mode but not dark`);
      }
      if (typeof lightValue !== 'string' && typeof lightValue !== 'number') {
        throw new Error(`${context}: token ${token.name} was not transformed to a CSS value`);
      }
      return [token.name, lightValue === darkValue ? lightValue : `light-dark(${lightValue}, ${darkValue})`];
    }),
  );
}

const base = await mergedValues('base');

const blocks = [
  `/* Generated by ${pkg.name} v${pkg.version}. Do not edit. */`,
  '/* Base :root is the shared resolution; each [data-situation] block holds that',
  "   situation's resolved deltas. Declare data-situation on <body> (or <html>);",
  '   regions may re-scope. See decisions/2026-07-20-reading-situations.md. */',
  ':root {',
  '  color-scheme: light dark;',
  ...[...base].map(([name, value]) => `  --${name}: ${value};`),
  '}',
];

for (const situation of matrix.situations) {
  const values = await mergedValues(situation);
  const missing = [...values.keys()].filter((name) => !base.has(name));
  if (missing.length || values.size !== base.size) {
    throw new Error(`${situation}: token set differs from base (overrides may only remap existing tokens): ${missing.join(', ')}`);
  }
  const delta = [...values].filter(([name, value]) => base.get(name) !== value);
  blocks.push('', `[data-situation="${situation}"] {`, ...delta.map(([name, value]) => `  --${name}: ${value};`), '}');
  console.log(`  ${situation}: ${delta.length} delta token${delta.length === 1 ? '' : 's'}`);
}

mkdirSync(path.join(ROOT, 'dist'), { recursive: true });
writeFileSync(path.join(ROOT, 'dist', 'tokens.css'), `${blocks.join('\n')}\n`);
console.log(`dist/tokens.css (${base.size} base tokens, ${matrix.situations.length} situations)`);
