import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const pkg = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

// Reset and base element styles apply only inside a declared reading
// situation; a page that declares none renders unmistakably broken
// (decisions/2026-07-20-reading-situations.md §3). The diagnostic's raw
// magenta is deliberate and exempt from the token-only rule: it is the one
// value that must read as "not design".
const CSS = `/* Generated by ${pkg.name} v${pkg.version}. Do not edit. */
/* Layers: sax-diagnostic (unconditional), sax-reset and sax-base (scoped to
   [data-situation]). Unlayered consumer rules always win over sax-reset and
   sax-base; the diagnostic uses !important because a missing situation must
   surface through any styling. */
@layer sax-diagnostic, sax-reset, sax-base;

@layer sax-diagnostic {
  html:not([data-situation]) > body:not([data-situation]) {
    background: repeating-linear-gradient(45deg, #f0f, #f0f 16px, #000 16px, #000 32px) !important;
  }
  html:not([data-situation]) > body:not([data-situation])::before {
    content: 'sax-design-system: no reading situation declared. Set data-situation="literary | documentation | marketing | presentation | application" on <body> or <html>.';
    display: block !important;
    margin: 1rem !important;
    padding: 1rem !important;
    border: 4px solid #f0f !important;
    background: #000 !important;
    color: #f0f !important;
    font: 700 1.25rem/1.4 monospace !important;
  }
}

@layer sax-reset {
  [data-situation],
  [data-situation] *,
  [data-situation] ::before,
  [data-situation] ::after {
    box-sizing: border-box;
  }
  [data-situation],
  [data-situation] * {
    margin: 0;
  }
  [data-situation] :is(img, picture, video, canvas, svg) {
    display: block;
    max-width: 100%;
  }
  [data-situation] :is(button, input, select, textarea) {
    font: inherit;
    color: inherit;
  }
}

@layer sax-base {
  [data-situation] {
    background: var(--color-background-page);
    color: var(--color-text-body);
    font: var(--typography-body);
  }
  [data-situation] main {
    max-width: var(--container-max);
    margin-inline: auto;
    padding-inline: var(--container-gutter);
  }
  [data-situation] h1 {
    font: var(--typography-heading-1);
    color: var(--color-text-heading);
  }
  [data-situation] h2 {
    font: var(--typography-heading-2);
    color: var(--color-text-heading);
  }
  [data-situation] :is(h3, h4, h5, h6) {
    font: var(--typography-heading-3);
    color: var(--color-text-heading);
  }
  [data-situation] :is(h1, h2, h3, h4, h5, h6) {
    margin-block-end: var(--rhythm-flow);
  }
  [data-situation] :is(h2, h3, h4, h5, h6):not(:first-child) {
    margin-block-start: var(--rhythm-section);
  }
  [data-situation] :is(p, ul, ol, dl, blockquote, pre, figure, table) {
    margin-block-end: var(--rhythm-flow);
  }
  [data-situation] a {
    color: var(--link-text);
  }
  [data-situation] a:hover {
    color: var(--link-text-hover);
  }
  [data-situation] :is(ul, ol) {
    padding-inline-start: var(--space-lg);
  }
  [data-situation] blockquote {
    border-inline-start: var(--border-width-thick) solid var(--color-accent-default);
    padding-inline-start: var(--space-md);
    color: var(--color-text-muted);
  }
  [data-situation] :is(code, kbd, samp) {
    font: var(--typography-code);
  }
  [data-situation] :not(pre) > code {
    background: var(--color-background-inset);
    border-radius: var(--radius-sm);
    padding-inline: var(--space-2xs);
  }
  [data-situation] pre {
    background: var(--color-background-inset);
    border: var(--border-width-default) solid var(--color-border-default);
    border-radius: var(--radius-md);
    padding: var(--space-md);
    overflow-x: auto;
  }
  [data-situation] hr {
    border: none;
    border-block-start: var(--border-width-default) solid var(--color-border-default);
    margin-block-end: var(--rhythm-flow);
  }
  [data-situation] table {
    border-collapse: collapse;
  }
  [data-situation] :is(th, td) {
    border: var(--border-width-default) solid var(--color-border-default);
    padding: var(--space-xs) var(--space-sm);
    text-align: start;
  }
  [data-situation] th {
    font: var(--typography-label);
    color: var(--color-text-heading);
  }
  [data-situation] button {
    font: var(--button-label-font);
    padding: var(--button-padding-block) var(--button-padding-inline);
    border: var(--border-width-default) solid var(--button-secondary-border);
    border-radius: var(--button-radius);
    background: var(--button-secondary-background);
    color: var(--button-secondary-text);
  }
  [data-situation] label {
    font: var(--input-label-font);
  }
  [data-situation] :is(input, select, textarea) {
    font: var(--input-value-font);
    padding: var(--input-padding-block) var(--input-padding-inline);
    border: var(--input-border-width) solid var(--input-border);
    border-radius: var(--input-radius);
    background: var(--input-background);
    color: var(--input-text);
  }
  [data-situation] ::placeholder {
    color: var(--input-placeholder);
  }
  [data-situation] :is(button, input, select, textarea):focus-visible {
    outline: var(--input-border-width-focus) solid var(--input-border-focus);
    outline-offset: 1px;
  }
  [data-situation] button:disabled {
    background: var(--button-disabled-background);
    color: var(--button-disabled-text);
    border-color: var(--input-disabled-border);
  }
  [data-situation] :is(input, select, textarea):disabled {
    background: var(--input-disabled-background);
    color: var(--input-disabled-text);
    border-color: var(--input-disabled-border);
  }
}
`;

mkdirSync(path.join(ROOT, 'dist'), { recursive: true });
writeFileSync(path.join(ROOT, 'dist', 'base.css'), CSS);
console.log('dist/base.css');
