import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { cssTokensFor, isPrimitive } from './lib/css-tokens.js';

const ROOT = path.resolve(import.meta.dirname, '..');
const matrix = JSON.parse(readFileSync(path.join(ROOT, 'config/matrix.json'), 'utf8'));
const pkg = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

if (matrix.modes.length !== 2 || !matrix.modes.includes('light') || !matrix.modes.includes('dark')) {
  throw new Error('CSS output assumes exactly the modes ["light", "dark"] (light-dark()).');
}

for (const product of matrix.products) {
  const [light, dark] = await Promise.all(
    ['light', 'dark'].map(async (mode) => (await cssTokensFor(product, mode)).filter((t) => !isPrimitive(t))),
  );
  const darkValues = new Map(dark.map((token) => [token.name, token.$value]));

  const declarations = light.map((token) => {
    const lightValue = token.$value;
    const darkValue = darkValues.get(token.name);
    if (darkValue === undefined) {
      throw new Error(`${product}: token ${token.name} exists in light mode but not dark`);
    }
    if (typeof lightValue !== 'string' && typeof lightValue !== 'number') {
      throw new Error(`${product}: token ${token.name} was not transformed to a CSS value`);
    }
    const value = lightValue === darkValue ? lightValue : `light-dark(${lightValue}, ${darkValue})`;
    return `  --${token.name}: ${value};`;
  });

  const css = [
    `/* Generated by ${pkg.name} v${pkg.version}. Do not edit. */`,
    ':root {',
    '  color-scheme: light dark;',
    ...declarations,
    '}',
    '',
  ].join('\n');

  const outDir = path.join(ROOT, 'dist', product);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(path.join(outDir, 'tokens.css'), css);
  console.log(`dist/${product}/tokens.css (${light.length} tokens)`);
}
